interface HTMLElementDeprecatedTagNameMap {
	acronym: HTMLElement
	applet: HTMLUnknownElement
	basefont: HTMLElement
	bgsound: HTMLUnknownElement
	big: HTMLElement
	blink: HTMLUnknownElement
	center: HTMLElement
	dir: HTMLDirectoryElement
	font: HTMLFontElement
	frame: HTMLFrameElement
	frameset: HTMLFrameSetElement
	isindex: HTMLUnknownElement
	keygen: HTMLUnknownElement
	listing: HTMLPreElement
	marquee: HTMLMarqueeElement
	menuitem: HTMLElement
	multicol: HTMLUnknownElement
	nextid: HTMLUnknownElement
	nobr: HTMLElement
	noembed: HTMLElement
	noframes: HTMLElement
	param: HTMLParamElement
	plaintext: HTMLElement
	rb: HTMLElement
	rtc: HTMLElement
	spacer: HTMLUnknownElement
	strike: HTMLElement
	tt: HTMLElement
	xmp: HTMLPreElement
}
